In [3]:
# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
# Create a vector with values ranging from 10 to 49.
import numpy as np
a = np.arange(10,50)
print("Original vector:")
print(a)

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
li = [1,2,0,0,4,0]
arr = np.array(li)
li_new = list(np.nonzero(arr)[0]) 
print(li_new)

[0, 1, 4]


In [7]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.94829542 0.95541625 0.50222294 0.44506269 0.71370977 0.59038546
  0.16925795 0.34347465 0.09898757 0.27861825]
 [0.54301783 0.67395524 0.87286699 0.34578749 0.53175202 0.61063401
  0.35535509 0.75652911 0.32002633 0.25268986]
 [0.22296073 0.04224443 0.83759806 0.10816555 0.39280693 0.3410265
  0.63723996 0.46469956 0.68015012 0.04366761]
 [0.97899812 0.00603975 0.43020609 0.6763646  0.15866486 0.49653793
  0.70187509 0.55480405 0.31618366 0.93543021]
 [0.52835194 0.3428685  0.72772183 0.0704054  0.71447115 0.23008959
  0.49853453 0.27595042 0.66975986 0.54581967]
 [0.51688903 0.44575938 0.40232895 0.51322715 0.16345721 0.88113954
  0.40833218 0.51792328 0.16076955 0.67224459]
 [0.58507526 0.66819034 0.21866271 0.56961859 0.45919759 0.48789564
  0.04418792 0.37492018 0.30929105 0.70629741]
 [0.29985853 0.19529287 0.86176642 0.65891145 0.47178847 0.50967124
  0.16376739 0.13642925 0.34780746 0.92297934]
 [0.87811821 0.06302538 0.36487471 0.92528668 0.44710148 0.498036

In [8]:
# 6. Create a random vector of size 30 and find the mean value
import numpy as np
x = np.random.random(30)
print("Original array:")
np.mean(x)

Original array:


0.43538511219788173